image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
  - ruby
  - ruby-dev
  - hut
environment:
  site: everyday-privacy.com
sources:
  - git+ssh://git@git.sr.ht/~timharek/everyday-privacy.com
triggers:
  - action: email
    condition: always
    to: tim@harek.no
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd $site
    bundle install
    bundle exec jekyll build
- package: |
    cd $site/_site
    tar -cvz . > ../../site.tar.gz
- deploy: |
    hut pages publish -d $site site.tar.gz

