title: Everyday Privacy
email: tim@harek.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://everyday-privacy.com" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: assets/_sass

# Build settings
plugins:
  - jekyll-feed
  - jekyll-datapage-generator

page_gen-dirs: false

page_gen:
  - data: 'service'
    template: 'service'
    name: 'name'
    dir: 'services'

exclude:
  - README.md
  - start.sh
  - report.md
  - report.pdf
