title: Everyday Privacy
email: tim@harek.dev
description: >-
  Your information is for sale. Your deepest secrets are being shared around the web. Take responsibility of your own data by learning more about what you give up and how you can still use the services you love without giving away too much.
baseurl: ""
url: "https://everyday-privacy.com"

sass:
  sass_dir: assets/_sass

github: https://github.com/timharek/everyday-privacy

collections:
  services:
    sort_by: name
    output: true
    permalink: /:collection/:title
  pwd_managers:
    sort_by: name
    output: false

defaults:
  - scope:
      path: ""
      types: "services"
    values:
      layout: "service"

# Build settings
plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - start.sh
