title: Everyday Privacy
email: tim@harek.no
description: >-
  Your data is up for sale. What you are doing and sharing around the web is being sold to advertiseres and other third-parties. Take responsibility of your own data by learning more about what you give up and how you can still use the services you love without giving away too much.
baseurl: ""
url: "https://everyday-privacy.com"

sass:
  sass_dir: assets/_sass

github: "https://github.com/timharek/everyday-privacy"
author:
  name: Tim Hårek Andreassen
  email: tim@harek.no

collections:
  services:
    sort_by: name
    output: true
    permalink: /:collection/:title
  pwd_managers:
    sort_by: name
    output: false

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

# Build settings
plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - start.sh
